/*
 * This file is generated by jOOQ.
 */
package eltex.tasks.database.tables.records;


import eltex.tasks.database.tables.UsersLanguages;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersLanguagesRecord extends TableRecordImpl<UsersLanguagesRecord> implements Record2<Long, Integer> {

    private static final long serialVersionUID = 512977865;

    /**
     * Setter for <code>users_languages.users_id</code>.
     */
    public void setUsersId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>users_languages.users_id</code>.
     */
    public Long getUsersId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>users_languages.lang_id</code>.
     */
    public void setLangId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>users_languages.lang_id</code>.
     */
    public Integer getLangId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return UsersLanguages.USERS_LANGUAGES.USERS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return UsersLanguages.USERS_LANGUAGES.LANG_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getUsersId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getLangId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getUsersId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getLangId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersLanguagesRecord value1(Long value) {
        setUsersId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersLanguagesRecord value2(Integer value) {
        setLangId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersLanguagesRecord values(Long value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsersLanguagesRecord
     */
    public UsersLanguagesRecord() {
        super(UsersLanguages.USERS_LANGUAGES);
    }

    /**
     * Create a detached, initialised UsersLanguagesRecord
     */
    public UsersLanguagesRecord(Long usersId, Integer langId) {
        super(UsersLanguages.USERS_LANGUAGES);

        set(0, usersId);
        set(1, langId);
    }
}
