/*
 * This file is generated by jOOQ.
 */
package eltex.tasks.database.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Passports implements Serializable {

    private static final long serialVersionUID = 1326958037;

    private final Long   id;
    private final String number;
    private final String series;

    public Passports(Passports value) {
        this.id = value.id;
        this.number = value.number;
        this.series = value.series;
    }

    public Passports(
        Long   id,
        String number,
        String series
    ) {
        this.id = id;
        this.number = number;
        this.series = series;
    }

    public Long getId() {
        return this.id;
    }

    public String getNumber() {
        return this.number;
    }

    public String getSeries() {
        return this.series;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Passports (");

        sb.append(id);
        sb.append(", ").append(number);
        sb.append(", ").append(series);

        sb.append(")");
        return sb.toString();
    }
}
