/*
 * This file is generated by jOOQ.
 */
package eltex.tasks.database.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Users implements Serializable {

    private static final long serialVersionUID = -268655967;

    private final Long   id;
    private final String fio;
    private final Long   addressId;
    private final Long   passportId;

    public Users(Users value) {
        this.id = value.id;
        this.fio = value.fio;
        this.addressId = value.addressId;
        this.passportId = value.passportId;
    }

    public Users(
        Long   id,
        String fio,
        Long   addressId,
        Long   passportId
    ) {
        this.id = id;
        this.fio = fio;
        this.addressId = addressId;
        this.passportId = passportId;
    }

    public Long getId() {
        return this.id;
    }

    public String getFio() {
        return this.fio;
    }

    public Long getAddressId() {
        return this.addressId;
    }

    public Long getPassportId() {
        return this.passportId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Users (");

        sb.append(id);
        sb.append(", ").append(fio);
        sb.append(", ").append(addressId);
        sb.append(", ").append(passportId);

        sb.append(")");
        return sb.toString();
    }
}
